In [3]:
x=5
y=1.0
z=str(y)
print(type(z))
print(type(x),type(y))

<class 'str'>
<class 'int'> <class 'float'>


In [4]:
s="KLH BOWREMPET"
print(s[:8])


KLH BOWR


In [5]:
s="KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION"
print(s[-10:-4])

FOUNDA


In [10]:
A="KONERU LAKSHMAIAHA EDUCATIONAL FOUNDATION"
print(A.lower())
print(A.find('R'))
print(A.capitalize())
print(A.swapcase())
print(A.title())
print(len(A))
print(A.replace('K','H'))
print("-".join(A))

koneru lakshmaiaha educational foundation
4
Koneru lakshmaiaha educational foundation
koneru lakshmaiaha educational foundation
Koneru Lakshmaiaha Educational Foundation
41
HONERU LAHSHMAIAHA EDUCATIONAL FOUNDATION
K-O-N-E-R-U- -L-A-K-S-H-M-A-I-A-H-A- -E-D-U-C-A-T-I-O-N-A-L- -F-O-U-N-D-A-T-I-O-N


In [14]:
a="KLH"
b="BOWREMPET"
c=a+" "+b
print(c)

KLH BOWREMPET


In [35]:
t1="Yhwatch"
t2="ICHIGO"
print(f"there are father and son {t1} and {t2}")


there are father and son Yhwatch and ICHIGO


In [26]:
a=5
b=10
if(a<b):
    print("a is lesser than b")
else:
    print("b is lesser than a")

a is lesser than b


In [34]:
a = 11
b = 5
c = 7
if (a > b and a > c):
    print("a is greater")
elif (b > a and b > c):
    print("b is greater")
else:
    print("c is greater")

a is greater


In [33]:
a=int(input())
if(a%2 == 0):
    print("EVEN")
else:
    print("ODD")

 2


EVEN


In [8]:
for i in range(1, 11):
    print("10 x", i, "=", 10 * i)

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100


In [40]:
for i in range(1, 101):
    if i % 2 == 0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [7]:
i = 1
while(i < 6):
    print(i)
    if(i == 4):
        break
    i += 1

1
2
3
4


In [6]:
i=0
while(i<6):
    i+=1
if(i==3):
    countinue 
    print(i)

In [9]:
import numpy as np
N=np.array([10,12,12,14])
print(type(N))

<class 'numpy.ndarray'>


In [31]:
import numpy as np
N = np.array([1,2,3,4,5,6])
print(N)
P = np.array([[1,2,3],
              [4,5,6]])
print(P)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np
P=np.zeros([1])
N=np.zeros([2,3])
print(P)
print((N))

[0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
import numpy as np
p=np.array([12,23,34,45,56,67,78])
print(p[0])
print(p[5])

12
67


In [14]:
import numpy as np
p=np.array([1,2,3,4,5])
print(p[-1])
p=np.array([[1,2,3],
               [4,5,6]])
print(p[-1,-1])
print(p[2:5])
print(p[:5])
print(p[4:])

5
6
[]
[[1 2 3]
 [4 5 6]]
[]


In [15]:
import numpy as np
n=np.array([1,2,3,4,5,6])
print(n.shape)
print(n.reshape(2,3))
print(n.reshape(3,2))
n.reshape(-1)

(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

In [16]:
import numpy as np
n=np.array([1,2,3,4,5,6])
for x in n:
        print(x)

           

1
2
3
4
5
6


In [17]:
import numpy as np
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in n:
        print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [18]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])
n3=np.concatenate((n1,n2))
print(n3)

[1 2 3 4 4 5 6 7]


In [19]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])
print(np.array_split(n3,4))

[array([1, 2]), array([3, 4]), array([4, 5]), array([6, 7])]


In [20]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])
n3=np.concatenate((n1,n2))
sp=np.array_split(n3,4)
print(sp[0])

[1 2]


In [22]:
import numpy as np
n1=np.array([4,2,3,4])
p=np.where(n1==4)
print(p)

(array([0, 3]),)


In [23]:
import numpy as np
n1=np.array([4,2,3,1])
p=np.sort(n1)
print(p)

[1 2 3 4]


In [24]:
import numpy as np
n=np.array(['hi','java','pyth','app'])
print(np.sort(n))

['app' 'hi' 'java' 'pyth']


In [25]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])
print(np.sum([n1,n2]))

32


In [28]:
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])
print(np.sum([n1,n2],axis=1))
print(np.sum([n1,n2],axis=0))

[10 22]
[ 5  7  9 11]


In [39]:
import pandas as pd
data={'apples':[3,2,0,1],'oranges':[0,3,7,2]}
df=pd.DataFrame(data)
print(df)
df=pd.DataFrame(data,index=['Ahmad','Ali','Rashed','Hamza'])
print(df)
data={'col_1':[3,2,1,0],'col_2':['a','b','c','d']}
pd.Dataprint(data)


   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2
        apples  oranges
Ahmad        3        0
Ali          2        3
Rashed       0        7
Hamza        1        2
{'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}


In [42]:
import pandas as ps
df = pd.read_csv(r"C:\Users\rathn\Downloads\Iris.csv")
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [43]:
print(df.head(10))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa


In [44]:
print(df.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris